apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "open-sail-tracker.fullname" . }}
  labels:
    {{- include "open-sail-tracker.labels" . | nindent 4 }}
    app.kubernetes.io/component: backend
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "open-sail-tracker.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "open-sail-tracker.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: backend
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: backend
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          args:
            - --port
            - {{ .Values.coapPort | quote }}
          {{- if .Values.victoriaMetrics.enabled }}
          env:
            - name: VICTORIA_METRICS_URL
              value: {{ .Values.victoriaMetrics.url | quote }}
            - name: STORAGE_QUEUE_SIZE
              value: {{ .Values.victoriaMetrics.queueSize | quote }}
          {{- end }}
          ports:
            - name: coap
              containerPort: {{ .Values.coapPort }}
              {{- if .Values.hostPort.enabled }}
              hostPort: {{ .Values.hostPort.port }}
              {{- with .Values.hostPort.hostIP }}
              hostIP: {{ . | quote }}
              {{- end }}
              {{- end }}
              protocol: UDP
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
