replicaCount: 1
coapPort: 39001

image:
  repository: ghcr.io/micw/open-sail-tracker-backend
  pullPolicy: IfNotPresent
  tag: ""

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

hostPort:
  enabled: true
  port: 39001
  hostIP: ""

service:
  enabled: false
  type: ClusterIP
  port: 39001
  externalIPs: []
  annotations: {}
  externalTrafficPolicy: ""

victoriaMetrics:
  enabled: true
  url: http://open-sail-tracker-vm:8428/api/v1/import/prometheus
  queryUrl: http://open-sail-tracker-vm:8428/api/v1/export
  queueSize: 10000

api:
  enabled: true
  replicaCount: 1
  service:
    type: ClusterIP
    port: 80
  ingress:
    enabled: true
    className: nginx
    host: sailtracker.wyraz.de
    path: /api
    pathType: Prefix
  resources:
    requests:
      cpu: 10m
      memory: 32Mi
    limits:
      cpu: 100m
      memory: 64Mi

web:
  enabled: true
  replicaCount: 1
  image:
    repository: ghcr.io/micw/open-sail-tracker-web
    pullPolicy: IfNotPresent
    tag: ""
  service:
    type: ClusterIP
    port: 80
  ingress:
    enabled: true
    className: nginx
    annotations:
      kubernetes.io/tls-acme: "true"
    host: sailtracker.wyraz.de
    path: /
    pathType: Prefix
    tls:
      enabled: true
      secretName: sailtracker-wyraz-de-tls
  resources:
    requests:
      cpu: 5m
      memory: 16Mi
    limits:
      cpu: 50m
      memory: 32Mi
  podSecurityContext:
    runAsNonRoot: true
    runAsUser: 101
    runAsGroup: 101
    fsGroup: 101
    seccompProfile:
      type: RuntimeDefault
  securityContext:
    allowPrivilegeEscalation: false
    capabilities:
      drop:
        - ALL
    readOnlyRootFilesystem: true

resources:
  requests:
    cpu: 10m
    memory: 32Mi
  limits:
    cpu: 100m
    memory: 64Mi

podSecurityContext:
  runAsNonRoot: true
  seccompProfile:
    type: RuntimeDefault

securityContext:
  allowPrivilegeEscalation: false
  capabilities:
    drop:
      - ALL
  readOnlyRootFilesystem: true
  runAsUser: 10001
  runAsGroup: 10001

nodeSelector: {}
tolerations: []
affinity: {}
