[platformio]
default_envs = h802-poc

[env:h802-poc]
platform = espressif32@6.12.0
framework = arduino
board = esp32-s3-wroom-1-n16r2
monitor_speed = 115200
upload_speed = 921600
build_flags =
    -DLILYGO_SIM7670G_S3_STAN
    -DLILYGO_SIMCOM_STANDARD_PIN
    -DARDUINO_USB_CDC_ON_BOOT=1
    -DCORE_DEBUG_LEVEL=0
